import type { Metadata } from "next";
import { Bebas_Neue, Montserrat } from "next/font/google";
import "./globals.css";

const dmSerifDisplay = Bebas_Neue({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400",
});

const dmMonserrat = Montserrat({
  variable: "--font-dm-montserrat",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSerifDisplay.variable} ${dmMonserrat.variable} antialiased bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
